In [39]:
from sklearn import datasets
from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import cross_val_predict
from sklearn import linear_model
import matplotlib.pyplot as plt
from sklearn import cross_validation
from sklearn.cross_validation import KFold
import numpy as np
import pandas as p
from sklearn import metrics 
from sklearn.metrics import mean_squared_error
data='/Users/rohit/Downloads/guid_02.csv'
df=p.read_csv(data)
df.rename(columns={'Change%': 'Change'}, inplace=True)
df.head(5)
del df['Date']
del df['Market']

In [40]:

Y=df.Volume
del df['Volume']
df.head(5)

Open        High         Low       Close    Change   Adj Close
0  109.809998  110.349998  108.830002  109.949997  0.139999  109.949997
1  106.699997  110.230003  106.599998  109.989998  3.290001  109.989998
2  106.570000  107.680000  106.160004  107.110001  0.540001  107.110001
3  107.709999  107.809998  104.080002  105.709999 -2.000000  105.709999
4  107.120003  108.870003  106.550003  108.430000  1.309997  108.430000

In [41]:

x = np.shape(df)
y = np.shape(Y)
kf_total = cross_validation.KFold(len(df), n_folds=10, shuffle=True,random_state=4)
kf_total
from sklearn.feature_selection import f_regression
feature=f_regression(df,Y,center=True)
feature[1]

array([  8.68893724e-04,   4.71111473e-03,   7.62106187e-05,
         6.37292188e-04,   5.42147525e-01,   2.94865293e-04])

In [42]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import median_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from math import sqrt
import datetime
import time
#kf_dict = dict([("fold_%s" % i,[]) for i in range(1, 10+1)])
kf_dict=[]
testMse=[]
fold=0

#print(pt,'\n')
truetime=0

for train_indices, test_indices in kf_total:
        regr_1 = DecisionTreeRegressor(min_samples_split=40,min_samples_leaf=15,max_leaf_nodes=25)
        regr_2 = DecisionTreeRegressor(max_depth=10)
        pt=time.clock()
        fold += 1
        #print ("Fold: %s" % fold)
        #pt=time.clock()
        X_train, X_test = df.ix[train_indices,:], df.ix[test_indices,:]
        y_train, y_test = Y[train_indices], Y[test_indices]
        lr = linear_model.LinearRegression()
        regr_1.fit(X_train,y_train)
        pt2=time.clock()
        t=pt2-pt
        truetime=truetime+t
        y_pred=regr_1.predict(X_test)
        rSqr=regr_1.score(X_test, y_test)
        rmse=sqrt(mean_squared_error(y_test,y_pred))
        kf_dict.append(rSqr)
        testMse.append(rmse)
        

              
print ('time taken to create model :', truetime)

a=0
for rSq in kf_dict:
    a=a+rSq
print ('R Squared value is :', a/len(kf_dict))

b=0
for rmse in testMse:
    b=b+rmse
print ('root mean squared error :' , b/len(testMse))

a=regr_1.tree_
print ("size of tree is :" ,a.node_count)

time taken to create model : 0.04443399999999986
R Squared value is : 0.200854251308
root mean squared error : 14317537.63702851
size of tree is : 15


In [43]:
regr_1.feature_importances_ 

array([ 0.        ,  0.00479641,  0.10610316,  0.        ,  0.86512377,
        0.02397667])

In [44]:
from sklearn import tree
import graphviz 
tree.export_graphviz(regr_1,out_file='stock',feature_names=df.columns) 
 
from graphviz import Digraph
from graphviz import dot

In [45]:
testdataset='/Users/rohit/Downloads/test.csv'
test=p.read_csv(testdataset)
test.head(10)

Date        Open        High         Low       Close   Change1  \
0  2016-12-01  110.370003  110.940002  109.029999  109.489998 -0.880005   
1  2016-11-30  111.599998  112.199997  110.269997  110.519997 -1.080001   
2  2016-11-29  110.779999  112.029999  110.070000  111.459999  0.680000   
3  2016-11-28  111.430000  112.470001  111.389999  111.570000  0.140000   
4  2016-11-25  111.129997  111.870003  110.949997  111.790001  0.660004   
5  2016-11-23  111.360001  111.510002  110.330002  111.230003 -0.129998   
6  2016-11-22  111.949997  112.419998  111.400002  111.800003 -0.149994   
7  2016-11-21  110.120003  111.989998  110.010002  111.730003  1.610000   
8  2016-11-18  109.720001  110.540001  109.660004  110.059998  0.339997   

     Volume   Adj Close Market  
0  36825800  109.489998    Low  
1  35765000  110.519997    Low  
2  28459300  111.459999   High  
3  27026600  111.570000   High  
4  11424400  111.790001   High  
5  27387900  111.230003    Low  
6  25922600  111.800003    Low  
7  29119100  111.730003   High  
8  27404300  110.059998   High

In [46]:


del test['Date']
del test['Market']

Y=test.Volume
del test['Volume']
test.head(10)

Open        High         Low       Close   Change1   Adj Close
0  110.370003  110.940002  109.029999  109.489998 -0.880005  109.489998
1  111.599998  112.199997  110.269997  110.519997 -1.080001  110.519997
2  110.779999  112.029999  110.070000  111.459999  0.680000  111.459999
3  111.430000  112.470001  111.389999  111.570000  0.140000  111.570000
4  111.129997  111.870003  110.949997  111.790001  0.660004  111.790001
5  111.360001  111.510002  110.330002  111.230003 -0.129998  111.230003
6  111.949997  112.419998  111.400002  111.800003 -0.149994  111.800003
7  110.120003  111.989998  110.010002  111.730003  1.610000  111.730003
8  109.720001  110.540001  109.660004  110.059998  0.339997  110.059998

In [47]:
#test.head(10)
Y

0    36825800
1    35765000
2    28459300
3    27026600
4    11424400
5    27387900
6    25922600
7    29119100
8    27404300
Name: Volume, dtype: int64

In [48]:

pr=regr_1.predict(test)

In [49]:
pr

array([ 25843373.07692308,  25843373.07692308,  35579946.15384615,
        25843373.07692308,  35579946.15384615,  25843373.07692308,
        25843373.07692308,  64467068.75      ,  25843373.07692308])

In [ ]:
#This one is model tree.
#Change%	Adj Close are important attributes to made the tree. 
#Volume prediction is not related to any other attribute so it is not good to predict the value of volume might be other attributes are required to predict volume.