In [72]:
from sklearn import cluster
from sklearn import preprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import pairwise_distances
import collections
import datetime
import time

df = pd.read_csv('/Users/rohit/Downloads/fivefinance.csv')
df["Adj Close"]
df.head(2)



df_target= pd.read_csv('/Users/rohit/Downloads/fivefinance1.csv')


df_target.head(2)


FY=1  FY=2  FY=3  FY=4  FY=5        Open        High         Low  \
0     0     0     0     0     1  109.169998  110.089996  108.849998   
1     0     0     0     0     1  110.370003  110.940002  109.029999   

        Close    Volume  'Adj Close'  Market  
0  109.900002  26409800   109.900002       1  
1  109.489998  36825800   109.489998       0

In [73]:
sns.set(style="white")


#corrmat = df_target.corr()
corrmat=df_target.corr()
# print(corrmat)
# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))
cmap = sns.diverging_palette(220, 10, as_cmap=True)

sns.heatmap(corrmat, vmax=.8, square=True)
plt.show()

In [50]:
# K means

# df = pd.get_dummies(df)
# df = preprocessing.normalize(df, norm='l2')
#df = pd.read_csv('/Users/rohit/Downloads/KDD/fivefinance.csv')


# Data_1 = df([])
Kmean_score = np.zeros((20,1))
for i in range(20):
    k_means = cluster.KMeans(n_clusters=i+1, random_state=0).fit(df)
    Kmean_score[i] = k_means.inertia_
Kmean_score = np.concatenate(Kmean_score)

# plt.figure(figsize=(10,5))
plt.plot(np.arange(1,21), Kmean_score, lw=2)
plt.xlabel('number of clusters')
plt.ylabel('SSE')
plt.title('Optimal cluster number by K means method')
plt.show()

In [74]:

df_adj=pd.DataFrame(df_target, columns=[ 'Close','Volume','Low', "'Adj Close'", 'Market'])
stock=pd.DataFrame(df_adj, columns=['Low', 'Close','Volume', "'Adj Close'"])
M=pd.DataFrame(stock, columns=[ 'Market'])
L=pd.DataFrame(stock, columns=[ 'Low'])
C=pd.DataFrame(stock, columns=[ 'Close'])
A = pd.DataFrame(stock, columns=[ "'Adj Close'"])
V=pd.DataFrame(stock, columns=[ 'Volume'])

In [75]:
# guiding question 1 
## K-means, 10 clusters
start_time = time.time()
k_1 = cluster.KMeans(n_clusters=10, random_state=0).fit(stock)
print(k_1.labels_)
print()
print(k_1.cluster_centers_)
print()
print(k_1.inertia_)
print ()
cluster_percentage = [0]*10
for i in range(10):
    print(collections.Counter(k_1.labels_)[i]*100/1239)



[4 4 4 ..., 6 0 6]

[[  2.71322593e+02   2.73413069e+02   5.96898280e+07   9.03766676e+01]
 [  5.34199757e+02   5.42061705e+02   1.50120235e+08   7.33593326e+01]
 [  5.27434400e+02   5.35898800e+02   2.41140032e+08   7.01593296e+01]
 [  4.70167640e+02   4.74388473e+02   9.63302833e+07   7.48010968e+01]
 [  1.08953755e+02   1.09663878e+02   3.03681233e+07   1.07587906e+02]
 [  5.25736156e+02   5.33216154e+02   1.90740828e+08   7.20025977e+01]
 [  4.00604724e+02   4.03628186e+02   7.57967604e+07   7.96867649e+01]
 [  5.08638561e+02   5.19729992e+02   3.28488100e+08   6.79523521e+01]
 [  4.89484286e+02   4.94567348e+02   1.21086308e+08   7.25959831e+01]
 [  1.78151096e+02   1.79490262e+02   4.55035311e+07   1.01780201e+02]]

5.6883215684e+16

15.254237288135593
6.618240516545601
2.017756255044391
11.62227602905569
19.774011299435028
3.1476997578692494
14.689265536723164
0.5649717514124294
7.909604519774011
18.401937046004843


In [76]:

df_pca = pd.DataFrame(df, columns=['Open', 'Close', 'High','Low'])

df_fY_1516=pd.DataFrame(df, columns=['FY=4', 'FY=5','Open', 'Close','Volume', "'Adj Close'"])

Y = pd.DataFrame(df, columns=[ "'Adj Close'"])
#Y.head(2)

Y1=pd.DataFrame(df_fY_1516, columns=[ 'FY=5'])
Y2=pd.DataFrame(df_fY_1516, columns=[ 'FY=4'])
#y=pd.DataFrame(df_1, columns=[ "'Adj Close'"])

a=pd.DataFrame(df_fY_1516, columns=[ 'Low'])
b=pd.DataFrame(df_fY_1516, columns=[ 'Close'])

In [77]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
fig = plt.figure(1, figsize=(8, 6))
ax = Axes3D(fig, elev=-150, azim=110)

X_reduced = PCA(n_components=3).fit_transform(stock)

#Use PCA not to reduce variance but to analyze it in 3 D
pca = PCA(n_components=3)
pca.fit(df)
i=0
while (i<3):
    print (pca.explained_variance_ratio_[i] *100) 
    i=i+1
    
# scatterplot of the data without performing k mean clustering : it shows that only one PCA component is enough to explain 
# the total variance in the data

    
ax.scatter(X_reduced[:, 0], X_reduced[:, 1], X_reduced[:, 2],c=A,
           cmap=plt.cm.Paired)

ax.set_title("First three PCA directions")
ax.set_xlabel("1st eigenvector")
ax.w_xaxis.set_ticklabels([])
ax.set_ylabel("2nd eigenvector")
ax.w_yaxis.set_ticklabels([])
ax.set_zlabel("3rd eigenvector")
ax.w_zaxis.set_ticklabels([])

plt.show()



99.9999999955
4.49610332215e-09
7.10831589013e-12


In [78]:
Y.ix[0,"'Adj Close'"]

nan

In [79]:
Data_1 = PCA(n_components=2).fit_transform(stock)
kmeans = cluster.KMeans( n_clusters=10, random_state=0)
j=kmeans.fit(Data_1)

print (j.cluster_centers_)
print ()
print(j.labels_)
print()
print(j.inertia_)
print ()
#print (Kmean)

[[ -1.83618841e+07  -7.84802889e+00]
 [  7.20685233e+07  -4.94814681e+01]
 [  1.63088320e+08   2.96275626e+02]
 [  1.82785712e+07  -1.55416257e+02]
 [ -4.76835888e+07   1.14826920e+02]
 [  1.12689116e+08   1.12978588e+02]
 [ -2.25495167e+06  -1.32047267e+02]
 [  2.50436388e+08   6.44054993e+02]
 [  4.30345961e+07  -9.18195129e+01]
 [ -3.25481810e+07   7.23577966e+01]]

[4 4 4 ..., 6 0 6]

5.68832156838e+16



In [80]:
# Plot of Principal component against Closing and lable against Adj Closing value 
import pylab as pl
Data_1 = PCA(n_components=2).fit_transform(stock)
pl.figure('Reference Plot')

pl.scatter(Data_1[:, 0],Data_1[:,1], c=A, color="blue")
pl.show()


In [81]:
kmeans = cluster.KMeans(n_clusters=10, random_state=111)
kmeans.fit(stock)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=111, tol=0.0001, verbose=0)

In [82]:
for i in range(0, Data_1.shape[0]):
    if (kmeans.labels_[i] == 0):
        c1 = pl.scatter(Data_1[i,0],Data_1[i,1],c='r')
    elif (kmeans.labels_[i] == 1):
        c2 = pl.scatter(Data_1[i,0], Data_1[i,1],c='g')
    elif (kmeans.labels_[i] ==2) :
        c3 = pl.scatter(Data_1[i,0],Data_1[i,1],c='b')
    elif (kmeans.labels_[i]==3) :
        c4 = pl.scatter(Data_1[i,0],Data_1[i,1],c='black')
    elif (kmeans.labels_[i] == 4):
        c5 = pl.scatter(Data_1[i,0],Data_1[i,1],c='orange')
    elif (kmeans.labels_[i] ==5) :
        c6 = pl.scatter(Data_1[i,0],Data_1[i,1],c='grey')
    elif (kmeans.labels_[i]==6) :
        c7 = pl.scatter(Data_1[i,0],Data_1[i,1],c='violet')
    elif (kmeans.labels_[i] == 7) :
        c8= pl.scatter(Data_1[i,0],Data_1[i,1],c='brown')
    elif (kmeans.labels_[i] == 8) :
        c9= pl.scatter(Data_1[i,0],Data_1[i,1],c='pink')
    elif (kmeans.labels_[i] == 9) :
        c10= pl.scatter(Data_1[i,0],Data_1[i,1],c='darkgreen')
   
        
pl.legend([c1, c2, c3,c4,c5,c6,c7,c8,c9,c10],['Cluster 1', 'Cluster 2','Cluster 3','Cluster 4', 'Cluster 5','Cluster 6','Cluster 7','Cluster 8', 'Cluster 9', 'Cluster 10'])
pl.title('K-means 10 clusters ')
pl.show()

In [83]:
for i in range(0, Data_1.shape[0]):
    if (kmeans.labels_[i] == 0):
        c1 = pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='r')
    elif (kmeans.labels_[i] == 1):
        c2 = pl.scatter(Data_1[i,0], A.ix[i,"'Adj Close'"],c='g')
    elif (kmeans.labels_[i] ==2) :
        c3 = pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='b')
    elif (kmeans.labels_[i]==3) :
        c4 = pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='black')
    elif (kmeans.labels_[i] == 4):
        c5 = pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='orange')
    elif (kmeans.labels_[i] ==5) :
        c6 = pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='grey')
    elif (kmeans.labels_[i]==6) :
        c7 = pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='violet')
    elif (kmeans.labels_[i] == 7) :
        c8= pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='brown')
    elif (kmeans.labels_[i] == 8) :
        c9= pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='pink')
    elif (kmeans.labels_[i] == 9) :
        c10= pl.scatter(Data_1[i,0],A.ix[i,"'Adj Close'"],c='darkgreen')
   
        
pl.legend([c1, c2, c3,c4,c5,c6,c7,c8,c9,c10],['Cluster 1', 'Cluster 2','Cluster 3','Cluster 4', 'Cluster 5','Cluster 6','Cluster 7','Cluster 8', 'Cluster 9', 'Cluster 10'])
pl.title('K-means 10 clusters ')
pl.show()

In [84]:
for i in range(0, Data_1.shape[0]):
    if (kmeans.labels_[i] == 0):
        c1 = pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='r')
    elif (kmeans.labels_[i] == 1):
        c2 = pl.scatter(Data_1[i,0], C.ix[i,'Close'],c='g')
    elif (kmeans.labels_[i] ==2) :
        c3 = pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='b')
    elif (kmeans.labels_[i]==3) :
        c4 = pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='black')
    elif (kmeans.labels_[i] == 4):
        c5 = pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='orange')
    elif (kmeans.labels_[i] ==5) :
        c6 = pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='grey')
    elif (kmeans.labels_[i]==6) :
        c7 = pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='violet')
    elif (kmeans.labels_[i] == 7) :
        c8= pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='yellow')
    elif (kmeans.labels_[i] == 8) :
        c9= pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='pink')
    elif (kmeans.labels_[i] == 9) :
        c10= pl.scatter(Data_1[i,0],C.ix[i,'Close'],c='darkgreen')
   
        
pl.legend([c1, c2, c3,c4,c5,c6,c7,c8,c9,c10],['Cluster 1', 'Cluster 2','Cluster 3','Cluster 4', 'Cluster 5','Cluster 6','Cluster 7','Cluster 8', 'Cluster 9', 'Cluster 10'])
pl.title('K-means clusters the Iris dataset into 8    clusters')
pl.show()   



In [85]:
for i in range(0, Data_1.shape[0]):
    if (kmeans.labels_[i] == 0):
        c1 = pl.scatter(V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='r')
    elif (kmeans.labels_[i] == 1):
        c2 = pl.scatter( V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='g')
    elif (kmeans.labels_[i] ==2) :
        c3 = pl.scatter(V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='b')
    elif (kmeans.labels_[i]==3) :
        c4 = pl.scatter(V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='black')
    elif (kmeans.labels_[i] == 4):
        c5 = pl.scatter(V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='orange')
    elif (kmeans.labels_[i] ==5) :
        c6 = pl.scatter(V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='grey')
    elif (kmeans.labels_[i]==6) :
        c7 = pl.scatter(V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='violet')
    elif (kmeans.labels_[i] == 7) :
        c8= pl.scatter(V.ix[i,'Volume'],Y.ix[i,"'Adj Close'"],c='yellow')
    elif (kmeans.labels_[i] == 8) :
        c9= pl.scatter(V.ix[i,'Volume'],A.ix[i,"'Adj Close'"],c='pink')
    elif (kmeans.labels_[i] == 9) :
        c10= pl.scatter(V.ix[i,'Volume'],A.ix[i,"'Adj Close'"],c='darkgreen')
   
        
pl.legend([c1, c2, c3,c4,c5,c6,c7,c8,c9,c10],['Cluster 1', 'Cluster 2','Cluster 3','Cluster 4', 'Cluster 5','Cluster 6','Cluster 7','Cluster 8', 'Cluster 9', 'Cluster 10'])
pl.title('K-means clusters the Iris dataset into 8    clusters')
pl.show()   



In [86]:
import pylab as pl
Data_1 = PCA(n_components=3).fit_transform(stock)

fig = plt.figure(1, figsize=(8, 6))
ax = Axes3D(fig, elev=-150, azim=110)
    
ax.scatter(Data_1[:, 0], Data_1[:, 1], Data_1[:, 2],c=A,
           cmap=plt.cm.Paired)

ax.set_title("First three PCA directions")
ax.set_xlabel("1st eigenvector")
ax.w_xaxis.set_ticklabels([])
ax.set_ylabel("2nd eigenvector")
ax.w_yaxis.set_ticklabels([])
ax.set_zlabel("3rd eigenvector")
ax.w_zaxis.set_ticklabels([])

plt.show()







In [87]:
start_time = time.time()
kmeans = cluster.KMeans(n_clusters=10)
kmeans.fit(stock)
Dat= PCA(n_components=1).fit_transform(stock)
pl.figure('K-means with 10 clusters')
fig = plt.figure(1, figsize=(8, 6))
ax = Axes3D(fig, elev=-150, azim=110)
ax.scatter(C.ix[:,'Close'], A.ix[:,"'Adj Close'"], Dat[:, 0],c=kmeans.labels_, cmap=plt.cm.Paired)

plt.show()
load_time_h_1 = time.time() - start_time
print (load_time_h_1)

5.810653924942017


In [88]:
from sklearn import metrics
metrics.calinski_harabaz_score(stock, kmeans.labels_)  

7520.9466875050011

# Hierarchy Clustering 

In [89]:
from scipy.cluster import hierarchy
from scipy.spatial import distance
start_time = time.time()
fig = plt.figure(figsize=(8,5))
Y = distance.pdist(stock)
Z = hierarchy.linkage(Y, method = "centroid", metric = "cosine")
T = hierarchy.fcluster(Z, 10, criterion = "maxclust",depth=10)
plt.title('Hierarchical Clustering Dendrogram ',fontsize=15)
plt.xlabel('sample index or (cluster size)',fontsize=10)
plt.ylabel('distance',fontsize=10)
hierarchy.dendrogram(Z,4,truncate_mode='level',orientation='top',show_contracted=True)
plt.show()
load_time_h_1 = time.time() - start_time
print (load_time_h_1)

3.835700035095215


In [90]:
plt.figure(figsize=(10, 8))
plt.scatter(stock.ix[:,'Close'], stock.ix[:,"'Adj Close'"], c=T, cmap='prism')  # plot points with cluster dependent colors
plt.show()

In [91]:
#ward euc
#centroid euc


In [92]:
from scipy.cluster import hierarchy
from scipy.spatial import distance
Y = distance.pdist(df)
Z = hierarchy.linkage(Y, method = "centroid", metric = "euclidean")
T = hierarchy.fcluster(Z, 7, criterion = "maxclust")
hierarchy.dendrogram(Z)
plt.show()

In [93]:
hierarchy.dendrogram(
    Z,
    truncate_mode='lastp',  # show only the last p merged clusters
    p=20,  # show only the last p merged clusters
    show_leaf_counts=False,  # otherwise numbers in brackets are counts
    leaf_rotation=90.,
    leaf_font_size=12.,
    show_contracted=True,  # to get a distribution impression in truncated branches
)
plt.show()